project:
  type: book

book:
  title: "Open Science Essentials"
  subtitle: "Ein Überblick zu offener Forschung mit ausgewählten Hands-on Vertiefungen"
  author: "Jürgen Schneider <br /><ju.schneider@dipf.de>"
  date: "17 Jan 2024"
  date-format: "DD MMMM YYYY"
  chapters:
    - index.qmd
    - part: open_access_0.qmd
      chapters: 
        - open_access_1.qmd
        - open_access_2.qmd
        - open_access_3.qmd
    - part: open_data_0.qmd
      chapters: 
        - open_data_1.qmd
        - open_data_2.qmd
        - open_data_3.qmd
    - part: inquiry_0.qmd
      chapters: 
        - inquiry_1.qmd
        - inquiry_2.qmd
        - inquiry_3.qmd
  appendices: 
    - references.qmd
    - credit.qmd
  page-navigation: true

number-depth: 1

bibliography: www/references.bib
csl: https://raw.githubusercontent.com/citation-style-language/styles/master/apa.csl
css: www/style.css

quarto:
  packages:
    - emoji
    - fontawesome

format:
  html:
    theme: cosmo
  pdf:
    documentclass: scrreprt

editor: source

comments:
  hypothesis: 
    theme: clean